CREATE TABLE BAG(
	ID NUMBER NOT NULL AUTO_INCREMENT,
	LABEL_CODE VARCHAR(255),
	PRIMARY KEY(ID)
);

CREATE TABLE PACK(
	ID NUMBER NOT NULL AUTO_INCREMENT,
	BAG_ID NUMBER NOT NULL,
	GTIN VARCHAR(14) NOT NULL,
	BATCH VARCHAR(20) NOT NULL,
	SERIAL_NUMBER VARCHAR(20) NOT NULL,
	EXPIRY_DATE DATE,
	DECOMMISSIONED BOOLEAN,
	PRIMARY KEY(ID),
	FOREIGN KEY (BAG_ID) references BAG(ID)
);
